In [109]:
# Loading the dataset using pandas
import pandas as pd
df = pd.read_csv('customer_shopping_data.csv')

In [110]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,41,Female,Sandals,Clothing,75.000,Montana,L,Silver,Summer,NaN,Yes,Express,No,No,92,Cash,Weekly
1,2,23,Male,Sunglasses,Footwear,115.200,Minnesota,M,Beige,Fall,3.5,Yes,Express,No,No,72,Cash,Fortnightly
2,2,23,Male,Shirt,Clothing,209.880,Minnesota,M,Violet,Fall,4.3,Yes,Express,Yes,Yes,72,Cash,Fortnightly
3,3,69,Male,Jacket,Footwear,64.680,Oklahoma,L,Indigo,Winter,4.9,Yes,Express,Yes,Yes,95,Credit Card,Weekly
4,3,69,Male,Jewelry,Clothing,117.450,Oklahoma,L,Black,Summer,3.3,Yes,Next Day Air,No,No,95,Credit Card,Weekly
5,3,69,Male,Hat,Clothing,186.480,Oklahoma,S,Green,Fall,3.2,Yes,Free Shipping,Yes,Yes,95,Credit Card,Weekly
6,4,64,Female,Blouse,Accessories,99.360,Mississippi,L,Magenta,Summer,NaN,No,Next Day Air,No,No,76,Cash,Bi-Weekly
7,4,64,Female,Belt,Clothing,79.704,Mississippi,M,Violet,Winter,3.1,No,Free Shipping,No,No,76,Cash,Bi-Weekly
8,4,64,Female,Gloves,Accessories,152.320,Mississippi,L,Gold,Summer,4.2,No,Free Shipping,Yes,Yes,76,Cash,Bi-Weekly
9,5,44,Male,Hat,Footwear,47.520,Massachusetts,XL,Beige,Spring,4.9,No,Free Shipping,Yes,Yes,42,Debit Card,Weekly

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             56000 non-null  int64
 1   Age                     56000 non-null  int64
 2   Gender                  56000 non-null  object
 3   Item Purchased          56000 non-null  object
 4   Category                56000 non-null  object
 5   Purchase Amount (USD)   56000 non-null  float64
 6   Location                56000 non-null  object
 7   Size                    56000 non-null  object
 8   Color                   56000 non-null  object
 9   Season                  56000 non-null  object
 10  Review Rating           50400 non-null  float64
 11  Subscription Status     56000 non-null  object
 12  Shipping Type           56000 non-null  object
 13  Discount Applied        56000 non-null  object
 14  Promo Code Used         56000 non-null  object
 15  Previous Purchases      56000 non-null  int64
 16  Payment Method          56000 non-null  object
 17  Frequency of Purchases  56000 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 7.7+ MB

In [112]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,56000.000000,56000.000000,56000,56000,56000,56000.000000,56000,56000,56000,56000,50400.000000,56000,56000,56000,56000,56000.000000,56000,56000
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Sandals,Outerwear,NaN,Washington,S,Lavender,Winter,NaN,Yes,Free Shipping,Yes,Yes,NaN,Credit Card,Weekly
freq,NaN,NaN,36504,2320,14093,NaN,1229,14164,2366,14111,NaN,39354,9529,36400,36400,NaN,16702,8178
mean,12999.759071,44.138679,NaN,NaN,NaN,136.082665,NaN,NaN,NaN,NaN,3.809304,NaN,NaN,NaN,NaN,49.694375,NaN,NaN
std,7502.065987,15.323072,NaN,NaN,NaN,78.200179,NaN,NaN,NaN,NaN,0.690952,NaN,NaN,NaN,NaN,28.768613,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,12.096000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,6521.000000,31.000000,NaN,NaN,NaN,73.920000,NaN,NaN,NaN,NaN,3.200000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
50%,12968.000000,44.000000,NaN,NaN,NaN,124.875000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,49.000000,NaN,NaN
75%,19541.250000,57.000000,NaN,NaN,NaN,184.500000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,75.000000,NaN,NaN
max,26000.000000,70.000000,NaN,NaN,NaN,477.600000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,99.000000,NaN,NaN

In [113]:
#checking whether any duplicates
df.duplicated().all()

np.False_

In [114]:
# Checking if missing data or null values are present in the dataset
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)        0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating             5600
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
dtype: int64

In [115]:
# Adding a new column with a flag if review rating is missing
df['review_rating_was_missing'] = df['Review Rating'].isna().astype(int)

In [116]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,review_rating_was_missing
0,1,41,Female,Sandals,Clothing,75.000,Montana,L,Silver,Summer,NaN,Yes,Express,No,No,92,Cash,Weekly,1
1,2,23,Male,Sunglasses,Footwear,115.200,Minnesota,M,Beige,Fall,3.5,Yes,Express,No,No,72,Cash,Fortnightly,0
2,2,23,Male,Shirt,Clothing,209.880,Minnesota,M,Violet,Fall,4.3,Yes,Express,Yes,Yes,72,Cash,Fortnightly,0
3,3,69,Male,Jacket,Footwear,64.680,Oklahoma,L,Indigo,Winter,4.9,Yes,Express,Yes,Yes,95,Credit Card,Weekly,0
4,3,69,Male,Jewelry,Clothing,117.450,Oklahoma,L,Black,Summer,3.3,Yes,Next Day Air,No,No,95,Credit Card,Weekly,0
5,3,69,Male,Hat,Clothing,186.480,Oklahoma,S,Green,Fall,3.2,Yes,Free Shipping,Yes,Yes,95,Credit Card,Weekly,0
6,4,64,Female,Blouse,Accessories,99.360,Mississippi,L,Magenta,Summer,NaN,No,Next Day Air,No,No,76,Cash,Bi-Weekly,1
7,4,64,Female,Belt,Clothing,79.704,Mississippi,M,Violet,Winter,3.1,No,Free Shipping,No,No,76,Cash,Bi-Weekly,0
8,4,64,Female,Gloves,Accessories,152.320,Mississippi,L,Gold,Summer,4.2,No,Free Shipping,Yes,Yes,76,Cash,Bi-Weekly,0
9,5,44,Male,Hat,Footwear,47.520,Massachusetts,XL,Beige,Spring,4.9,No,Free Shipping,Yes,Yes,42,Debit Card,Weekly,0

In [117]:
# Filling missing values in 'Review Rating' column with the median rating of the product category
df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

0        3.8
1        3.5
2        4.3
3        4.9
4        3.3
        ...
55995    3.8
55996    4.9
55997    4.9
55998    3.9
55999    3.0
Name: Review Rating, Length: 56000, dtype: float64

In [118]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [119]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)        0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
review_rating_was_missing    0
dtype: int64

In [120]:
# Converting column names to snake case
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [121]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases',
       'review_rating_was_missing'],
      dtype='object')

In [122]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [123]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases',
       'review_rating_was_missing'],
      dtype='object')

In [124]:
# create a new column 'age_group' based on 4 age groups
bins =[0,12,19,59,100]
labels=['Child','Teenager','Adult','Senior']
df['age_group']=pd.cut(df['age'],bins=bins,labels=labels)

In [125]:
df[['age','age_group']].head(10)

   age age_group
0   41     Adult
1   23     Adult
2   23     Adult
3   69    Senior
4   69    Senior
5   69    Senior
6   64    Senior
7   64    Senior
8   64    Senior
9   44     Adult

In [126]:
df['frequency_of_purchases'].unique()

array(['Weekly', 'Fortnightly', 'Bi-Weekly', 'Monthly', 'Annually',
       'Quarterly', 'Every 3 Months'], dtype=object)

In [127]:
# create new column based on "frequency_of_purchases"

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [128]:
df[['purchase_frequency_days','frequency_of_purchases']].head(15)

    purchase_frequency_days frequency_of_purchases
0                         7                 Weekly
1                        14            Fortnightly
2                        14            Fortnightly
3                         7                 Weekly
4                         7                 Weekly
5                         7                 Weekly
6                        14              Bi-Weekly
7                        14              Bi-Weekly
8                        14              Bi-Weekly
9                         7                 Weekly
10                        7                 Weekly
11                        7                 Weekly
12                       30                Monthly
13                       30                Monthly
14                      365               Annually

In [129]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0               No              No
1               No              No
2              Yes             Yes
3              Yes             Yes
4               No              No
5              Yes             Yes
6               No              No
7               No              No
8              Yes             Yes
9              Yes             Yes

In [130]:
#check whether column 'discount_applied' and 'promo_code_used' are same?
if (df['discount_applied'] == df['promo_code_used']).all():
    print("All matched")

All matched

In [131]:
#Dropping a dupliacte column
df=df.drop('promo_code_used',axis=1)

In [132]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,review_rating_was_missing,age_group,purchase_frequency_days
0,1,41,Female,Sandals,Clothing,75.000,Montana,L,Silver,Summer,3.8,Yes,Express,No,92,Cash,Weekly,1,Adult,7
1,2,23,Male,Sunglasses,Footwear,115.200,Minnesota,M,Beige,Fall,3.5,Yes,Express,No,72,Cash,Fortnightly,0,Adult,14
2,2,23,Male,Shirt,Clothing,209.880,Minnesota,M,Violet,Fall,4.3,Yes,Express,Yes,72,Cash,Fortnightly,0,Adult,14
3,3,69,Male,Jacket,Footwear,64.680,Oklahoma,L,Indigo,Winter,4.9,Yes,Express,Yes,95,Credit Card,Weekly,0,Senior,7
4,3,69,Male,Jewelry,Clothing,117.450,Oklahoma,L,Black,Summer,3.3,Yes,Next Day Air,No,95,Credit Card,Weekly,0,Senior,7
5,3,69,Male,Hat,Clothing,186.480,Oklahoma,S,Green,Fall,3.2,Yes,Free Shipping,Yes,95,Credit Card,Weekly,0,Senior,7
6,4,64,Female,Blouse,Accessories,99.360,Mississippi,L,Magenta,Summer,3.8,No,Next Day Air,No,76,Cash,Bi-Weekly,1,Senior,14
7,4,64,Female,Belt,Clothing,79.704,Mississippi,M,Violet,Winter,3.1,No,Free Shipping,No,76,Cash,Bi-Weekly,0,Senior,14
8,4,64,Female,Gloves,Accessories,152.320,Mississippi,L,Gold,Summer,4.2,No,Free Shipping,Yes,76,Cash,Bi-Weekly,0,Senior,14
9,5,44,Male,Hat,Footwear,47.520,Massachusetts,XL,Beige,Spring,4.9,No,Free Shipping,Yes,42,Debit Card,Weekly,0,Adult,7

In [133]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.13.2)

In [134]:
%pip install --upgrade pip

Requirement already satisfied: pip in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (26.0.1)
Note: you may need to restart the kernel to use updated packages.

In [135]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "customer_shopping_db"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer_shopping"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer_shopping LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,review_rating_was_missing,age_group,purchase_frequency_days
0,1,41,Female,Sandals,Clothing,75.00,Montana,L,Silver,Summer,3.8,Yes,Express,No,92,Cash,Weekly,1,Adult,7
1,2,23,Male,Sunglasses,Footwear,115.20,Minnesota,M,Beige,Fall,3.5,Yes,Express,No,72,Cash,Fortnightly,0,Adult,14
2,2,23,Male,Shirt,Clothing,209.88,Minnesota,M,Violet,Fall,4.3,Yes,Express,Yes,72,Cash,Fortnightly,0,Adult,14
3,3,69,Male,Jacket,Footwear,64.68,Oklahoma,L,Indigo,Winter,4.9,Yes,Express,Yes,95,Credit Card,Weekly,0,Senior,7
4,3,69,Male,Jewelry,Clothing,117.45,Oklahoma,L,Black,Summer,3.3,Yes,Next Day Air,No,95,Credit Card,Weekly,0,Senior,7